[phases.setup]
npmInstall = false

[phases.build]
buildCommand = "npm install && npx prisma generate --schema=prisma/schema.postgresql.prisma && npm run build"

[deploy]
startCommand = "node dist/server.js"
